// components/Layout.js
import Head from "next/head";
import { Stack, Heading } from "@chakra-ui/react";
import CustomBreadcrumb from "@/components/custom/custom-breadcrumb";

export default function ContactUs() {
  return (
    <>
      <Head>
        <title>Contact Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack gap={0} p={4}>
        <CustomBreadcrumb
          data={{
            root: "home",
            first: "contact-us"
          }}
        />
        <Heading>Contact Us</Heading>
      </Stack>
    </>
  );
}
