// components/Layout.js
import Head from "next/head";
import { Stack, Heading } from "@chakra-ui/react";

export default function FAQs() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack gap={0} p={4}>
        <Heading>FAQs</Heading>
      </Stack>
    </>
  );
}
