// components/Layout.js
import Head from "next/head";
import { Stack, Heading, SimpleGrid, Card, Field, Input, Flex, Button} from "@chakra-ui/react";
import CustomBreadcrumb from "@/components/custom/custom-breadcrumb";

export default function LoginPage() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack gap={4} p={4}>
        <CustomBreadcrumb
          data={{
            root: "home",
            first: "login"
          }}
        />
        <Heading size="3xl" color="#0030FF">Welcome Back!</Heading>
        <Stack>

        </Stack>
        
      </Stack>
    </>
  );
}
