// components/Layout.js
import Head from "next/head";
import { Stack, Flex, Box, InputGroup, Input, Drawer, Heading, CloseButton, Portal, Separator, Image, NumberInput, HStack, IconButton } from "@chakra-ui/react";
import { FaMapMarkerAlt, FaSearch } from "react-icons/fa";
import { PiShoppingCartBold, PiHeartBold } from "react-icons/pi";
import { Icon, Text, Button } from "@chakra-ui/react";
import SideNavigation from "./custom/side-navigation";
import FooterNavigation from "./custom/footer-navigation";
import { useEffect, useState } from "react";
import Link from "next/link";
import { CgPushChevronRight, CgClose, CgMathMinus, CgMathPlus, CgTrash } from "react-icons/cg";

export default function Layout({ children }) {
  const [open, setOpen] = useState(false)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="row">
        <Stack gap={0} flex={1}>
          {/* HEADER */}
          <Flex position="sticky" top="0" height="10dvh" alignItems="center" gap={8} p={4} backgroundColor="#0030FF">
            <Flex w="350px" justifyContent="center">
              <Image src="/images/smlogo.webp" height="50px" alt="Logo" />
            </Flex>
            <Flex alignItems="center" gap={2} color="#fff">
              <Icon size="xl" color="#fff">
                <FaMapMarkerAlt />
              </Icon>
              <Stack gap={0} >
                <Text fontSize="14px" fontWeight="bold">SM Supermarket Aura Premier</Text>
                <Text fontSize="10px">Metro Manila, Taguig City</Text>
              </Stack>
            </Flex>
            <Flex flex={1}>
              <InputGroup endElement={<FaSearch />}>
                <Input size="xl" backgroundColor="#fff" type="search" placeholder="Search for items here..." />
              </InputGroup>
            </Flex>
            <Flex gap={4} alignItems="center">
              <Link href="/login" passHref>
                <Button size="xl" color="#0030FF" backgroundColor="#fff" fontWeight="semibold">Hello, sign in?</Button>
              </Link>
              {/* <Menu.Root>
                <Menu.Trigger asChild>
                  <Button fontWeight="bold" fontSize="14px" size="xl" variant="plain" color="#0030FF" backgroundColor="#fff">My Account</Button>
                </Menu.Trigger>
                <Portal>
                  <Menu.Positioner>
                    <Menu.Content>
                      <Menu.Item value="my-account"><Link href="my-account">My Account</Link></Menu.Item>
                      <Menu.Item value="address-book"><Link href="address-book">Address Book</Link></Menu.Item>
                      <Menu.Item value="order"><Link href="order">Order</Link></Menu.Item>
                      <Menu.Item value="order-again"><Link href="order-again">Order Again</Link></Menu.Item>
                      <Menu.Item value="my-wishlist">My Wishlist</Menu.Item>
                      <Menu.Item value="newsletter-subscriptions">Newsletter Subscriptions</Menu.Item>
                      <Menu.Item value="logout">Logout</Menu.Item>
                    </Menu.Content>
                  </Menu.Positioner>
                </Portal>
              </Menu.Root> */}
              <Icon size="xl" color="#fff">
                <PiHeartBold />
              </Icon>
              <Drawer.Root open={open} onOpenChange={(e) => setOpen(e.open)}>
                <Drawer.Trigger asChild>
                  <Icon size="xl" color="#fff" cursor="pointer" onClick={() => setOpen(true)}>
                    <PiShoppingCartBold />
                  </Icon>
                </Drawer.Trigger>
                <Portal>
                  <Drawer.Backdrop />
                  <Drawer.Positioner>
                    <Drawer.Content>
                      <Drawer.Header>
                        <Drawer.Title>My Cart</Drawer.Title>
                      </Drawer.Header>
                      <Drawer.Body>
                        <p>
                          No item to show.
                        </p>
                      </Drawer.Body>
                      <Drawer.Footer>
                        <Button w="full" bgColor="smblue">Checkout</Button>
                      </Drawer.Footer>
                      <Drawer.CloseTrigger asChild>
                        <CloseButton size="sm" />
                      </Drawer.CloseTrigger>
                    </Drawer.Content>
                  </Drawer.Positioner>
                </Portal>
              </Drawer.Root>
            </Flex>
          </Flex>

          {/* LAYOUT GRID */}
          <Flex direction="row">
            <SideNavigation />
            <Stack height="90dvh" backgroundColor="#F5F5F5" flex={1} overflowY="auto">
              {children}
              <FooterNavigation />
            </Stack>
          </Flex>
        </Stack>
      </Flex>
    </>
  );
}
