// components/Layout.js
import Head from "next/head";
import { Stack, Flex, Box, InputGroup, Input, SimpleGrid } from "@chakra-ui/react";
import { FaMapMarkerAlt, FaSearch } from "react-icons/fa";
import { PiShoppingCartBold, PiHeartBold } from "react-icons/pi";
import Image from "next/image";
import { Icon, Text, Button } from "@chakra-ui/react";
import SideNavigation from "./custom/side-navigation";

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack gap={0}>
        {/* HEADER */}
        <Flex position="sticky" top="0" height="10dvh" alignItems="center" gap={8} p={4} pr={20} backgroundColor="#0030FF">
          <Box w="12%">
            <Image src="/images/smlogo.webp" width={250} height={40} alt="Logo" />
          </Box>
          <Flex alignItems="center" gap={2} color="#fff">
            <Icon size="xl" color="#fff">
              <FaMapMarkerAlt />
            </Icon>
            <Stack gap={0} >
              <Text fontSize="14px" fontWeight="bold">SM Supermarket Aura Premier</Text>
              <Text fontSize="10px">Metro Manila, Taguig City</Text>
            </Stack>
          </Flex>
          <Flex flex={1}>
            <InputGroup endElement={<FaSearch />}>
              <Input size="xl" backgroundColor="#fff" type="search" placeholder="Search for items here..."/>            
            </InputGroup>
          </Flex>
          <Flex gap={4} alignItems="center">
            <Button fontWeight="bold" fontSize="14px" size="xl" variant="plain" color="#0030FF" backgroundColor="#fff">My Account</Button>
            <Icon size="xl" color="#fff">
              <PiShoppingCartBold />
            </Icon>
            <Icon size="xl" color="#fff">
              <PiHeartBold />
            </Icon>
          </Flex>
        </Flex>

        {/* LAYOUT GRID */}
        <SimpleGrid templateColumns="17% 83%">
          <SideNavigation />
          <Stack w="full" p={4} backgroundColor="#F5F5F5">
            {children} {/* 👈 THIS IS WHERE CATEGORY CONTENT RENDERS */}
          </Stack>
        </SimpleGrid>
      </Stack>
    </>
  );
}
